service: connecting-the-dots

provider:
  name: aws
  runtime: python3.13  # Change to the correct Python version installed in the virtual environment

functions:
  app:
    handler: app.app
    events:
      - http:
          path: /
          method: GET
      - http:
          path: contact
          method: GET
      - http:
          path: dashboard
          method: GET
      - http:
          path: submit_contact
          method: POST

plugins:
  - serverless-wsgi

custom:
  wsgi:
    app: 'app.app'
    pythonBin: '/Users/mac1/Desktop/aws_cloud/Cloud Projects/AWS-Automation-with-Python-Boto3-and-Lambda-Projects/.venv/bin/python'
    packRequirements: true